name: http_test_server
description: "Dart package for testing HTTP requests and responses. Creates a simple HTTP server that responds with a specified response."
version: 0.1.1
homepage: https://github.com/femrek/http_test_server

environment:
  sdk: ^3.6.0

dev_dependencies:
  test: ^1.29.0
  very_good_analysis: ^10.0.0
